<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>StencilPad.Desktop</RootNamespace>
    <AssemblyName>StencilPad.Desktop</AssemblyName>
    <AssemblyTitle>StencilPad.Desktop</AssemblyTitle>
    <ApplicationIcon>..\StencilPad\Resources\StencilPad.ico</ApplicationIcon>
    <PackageIcon>StencilPad.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StencilPad\StencilPad.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows'))">
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <DefineConstants>$(DefineConstants);SP_WINDOWS</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('windows'))">
    <ProjectReference Include="..\StencilPad.Windows\StencilPad.Windows.csproj" />
  </ItemGroup>
  
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('linux'))">
    <TargetFrameworks>net10.0</TargetFrameworks>
    <DefineConstants>$(DefineConstants);SP_LINUX</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('linux'))">
    <ProjectReference Include="..\StencilPad.Linux\StencilPad.Linux.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('osx'))">
    <TargetFrameworks>net10.0-macos</TargetFrameworks>
    <DefineConstants>$(DefineConstants);SP_OSX</DefineConstants>
    <InfoPlist>Info.plist</InfoPlist>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('osx'))">
    <ProjectReference Include="..\StencilPad.OSX\StencilPad.OSX.csproj" />
  </ItemGroup>
  
</Project>
