<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-macos</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>StencilPad.OSX</RootNamespace>
    <AssemblyName>StencilPad.OSX</AssemblyName>
    <AssemblyTitle>StencilPad.OSX</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StencilPad\StencilPad.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('osx'))">
    <DefineConstants>$(DefineConstants);SP_OSX</DefineConstants>
  </PropertyGroup>

</Project>
