<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-macos</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>StencilPad.OSX</RootNamespace>
    <AssemblyName>StencilPad.OSX</AssemblyName>
    <AssemblyTitle>StencilPad.OSX</AssemblyTitle>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StencilPad\StencilPad.csproj" />
  </ItemGroup>

</Project>
